---
title: "final_project"
author: "Craig Heath, Harrison Holt, Asher Margulies, and Jim Tinley"
date: "2023-05-17"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(data.table)
library(tidyverse) 
library(corrplot)
library(kableExtra)
library(psych)
library(writexl)
library(gamlr)
library(glmnet)
library(randomForest)
library(caret)
library(smotefamily)
library(mltools)
```

```{r}
diab_dt <- fread("diabetic_data.csv")
ids_lookup_dt <- fread("IDs_mapping.csv")
```



```{r}
# DATA EXPLORATION
```

```{r}
str(diab_dt)
```

```{r}
# unique_vals <- sapply(diab_dt[,3:50], function(x) unique(x))
# unique_vals

# Checking unique counts to see # of levels for factor variables
unique_counts <- sapply(diab_dt, function(x) length(unique(x)))
unique_counts
```
```{r}
# In particular, drug data has low-level of observations for each factor.
drug_cols <- diab_dt[,25:47]

# Creating a table that shows counts for each level for drug columns
drug_levels_dt <- diab_dt[, lapply(.SD, function(x) table(factor(x, levels = c("No", "Up", "Down", "Steady")))), .SDcols = colnames(drug_cols)]

print(drug_levels_dt)
```



```{r}
# DATA WRANGLING
```

```{r}
# restructuring ids lookup tables as 3 separate tables
admission_ids_lookup_dt <- ids_lookup_dt[1:8]
setnames(admission_ids_lookup_dt, 
         names(admission_ids_lookup_dt), 
         c("admission_type_id","admission_type"))

discharge_ids_lookup_dt <- ids_lookup_dt[10:40]
setnames(discharge_ids_lookup_dt, 
         names(discharge_ids_lookup_dt), 
         c("discharge_disposition_id","discharge_type"))
discharge_ids_lookup_dt <- discharge_ids_lookup_dt[-1]

admission_source_ids_lookup_dt <- ids_lookup_dt[42:67]
setnames(admission_source_ids_lookup_dt, 
         names(admission_source_ids_lookup_dt), 
         c("admission_source_id","admission_source"))
admission_source_ids_lookup_dt <- admission_source_ids_lookup_dt[-1]

# removing old table
rm(ids_lookup_dt)
```


```{r}
# Joining ID lookup values with main feature dataset

setkey(diab_dt, admission_type_id)
setkey(admission_ids_lookup_dt, admission_type_id)
admission_ids_lookup_dt$admission_type_id <-
  as.integer(admission_ids_lookup_dt$admission_type_id)

diab_dt <- merge(diab_dt, admission_ids_lookup_dt, all.x = TRUE)

setkey(diab_dt, discharge_disposition_id)
setkey(discharge_ids_lookup_dt, discharge_disposition_id)
discharge_ids_lookup_dt$discharge_disposition_id <-
  as.integer(discharge_ids_lookup_dt$discharge_disposition_id)

diab_dt <- merge(diab_dt, discharge_ids_lookup_dt, all.x = TRUE)

setkey(diab_dt, admission_source_id)
setkey(admission_source_ids_lookup_dt, admission_source_id)
admission_source_ids_lookup_dt$admission_source_id <-
  as.integer(admission_source_ids_lookup_dt$admission_source_id)

diab_dt <- merge(diab_dt, admission_source_ids_lookup_dt, all.x = TRUE)


# resetting key in main feature data table back to encounter id
setkey(diab_dt, encounter_id)


# dropping 3 numeric id columns
diab_dt <- diab_dt[, -c("admission_type_id", "admission_source_id", "discharge_disposition_id")]
```

```{r}
# creating Unfavorable_Outcome variable - Expired/Hospice
diab_dt[, unfavorable_outcome := 
          ifelse((discharge_type == "Expired" | 
                   discharge_type == "Hospice / home" |
                    discharge_type == "Hospice / medical facility" | 
                     discharge_type == "Expired in a medical facility. Medicaid only, hospice." | 
                      discharge_type == "Expired - at home. Medicaid only, hospice."), 1, 0)]
```

```{r}
# removing categorical variables with only 1 level OR where there is <50 total observations in the other levels. These will likely only have one factor after removing NAs in other features of interest.

diab_dt <- diab_dt[, -c("acetohexamide", 
                        "citoglipton",
                        "examide",
                        "glipizide-metformin",
                        "glimepiride-pioglitazone", 
                        "metformin-pioglitazone",
                        "metformin-rosiglitazone",
                        "miglitol",
                        "tolbutamide",
                        "tolazamide",
                        "troglitazone")]
```

```{r}
# replacing "?"/"None"/"Unknown/Invalid" with NAs
diab_dt$gender <- 
    ifelse(diab_dt$gender == "Unknown/Invalid", NA, 
           ifelse(diab_dt$gender == "Female", 1, 0))
setnames(diab_dt, "gender", "gender_female")
diab_dt$race <- 
    ifelse(diab_dt$race == "?", NA, diab_dt$race)
diab_dt$payer_code <- 
    ifelse(diab_dt$payer_code == "?", NA, diab_dt$payer_code)
diab_dt$weight <- 
    ifelse(diab_dt$weight == "?", NA, diab_dt$weight)
diab_dt$medical_specialty <- 
    ifelse(diab_dt$medical_specialty == "?", NA, diab_dt$medical_specialty)
diab_dt$diag_1 <- 
    ifelse(diab_dt$diag_1 == "?", NA, diab_dt$diag_1)
diab_dt$diag_2 <- 
    ifelse(diab_dt$diag_2 == "?", NA, diab_dt$diag_2)
diab_dt$diag_3 <- 
    ifelse(diab_dt$diag_3 == "?", NA, diab_dt$diag_3)
diab_dt$admission_type <- 
    ifelse(diab_dt$admission_type == "NULL", NA, diab_dt$admission_type)
diab_dt$admission_source <- 
    ifelse(diab_dt$admission_source == "NULL", NA, diab_dt$admission_source)
diab_dt$discharge_type <- 
    ifelse(diab_dt$discharge_type == "NULL", NA, diab_dt$discharge_type)
```

```{r}
# number of NAs
na_count <- data.table(variable = names(diab_dt), 
                       count  = colSums(is.na(diab_dt)))
```

```{r}
# replacing Yes/No binaries with 1/0 
diab_dt$change <- 
    factor(ifelse(diab_dt$change== "No", 0, 1))
diab_dt$diabetesMed <- 
    factor(ifelse(diab_dt$diabetesMed== "No", 0, 1))
```

```{r}
# creating binary_readmitted outcome variable
diab_dt <- 
    diab_dt[, readmitted_binary := factor(ifelse(readmitted == "NO", 0, 1))]
```

```{r}
# Creating binary A1Cresult_measured treatment variable
diab_dt$A1Cresult_measured <- 
    factor(ifelse(diab_dt$A1Cresult == "None", 0, 1))
```




```{r}
# INFERENCE Q1: Does AIC Measurement affect readmission?
```

```{r}
# removing columns with large number of NAs. While it may be useful to control for weight and medical specialty, it is probably not worth reducing our sample size so dramatically. 
# Also for this question using binaries for A1Cresult and readmitted so dropping the actual cols

A1C_inference1_dt <- diab_dt[, -c("payer_code", 
                                  "medical_specialty", 
                                  "weight", 
                                  "diag_1", 
                                  "diag_2", 
                                  "diag_3", 
                                  "A1Cresult", 
                                  "readmitted",
                                  "discharge_type",
                                  "admission_source",
                                  "admission_type")] 
```

```{r}
# Removing NAs in all other variables
A1C_inference1_dt <- A1C_inference1_dt[complete.cases(A1C_inference1_dt)]
```

```{r}
# IDing cols for dummy variables (this is necessary if we want to SMOTE-NC/KNN)
A1C_char_columns <- A1C_inference1_dt[, c(Filter(is.character, .SD),
                                          .("encounter_id" = encounter_id))]

# Converting character cols to factor type (needed for one_hot formula)
char_vars <- sapply(A1C_char_columns, is.character)
char_cols <- names(A1C_char_columns)[char_vars]
A1C_char_columns[, (char_cols) := lapply(.SD, as.factor), .SDcols = char_cols]

# One-hot for dummy variables (NOTE: this creates R not R-1 dummies)
A1C_char_columns <- one_hot(A1C_char_columns)
```

```{r}
# Intuitively removing variables to create R-1 dummies/set baseline vars
# this is important for our interpretation of model effects
A1C_char_columns <- A1C_char_columns[, -c("race_Caucasian",
                                          "age_[0-10)",
                                          "max_glu_serum_None",
                                          "metformin_No",
                                          "repaglinide_No",
                                          "nateglinide_No",
                                          "chlorpropamide_No",
                                          "glimepiride_No",
                                          "glipizide_No",
                                          "glyburide_No",
                                          "pioglitazone_No",
                                          "rosiglitazone_No",
                                          "acarbose_No",
                                          "insulin_No",
                                          "glyburide-metformin_No")]
```

```{r}
setkey(A1C_char_columns, encounter_id)
setkey(A1C_inference1_dt, encounter_id)

A1C_inference1_dt <- merge(A1C_inference1_dt[,-c("race",
                                          "age",
                                          "max_glu_serum",
                                          "metformin",
                                          "repaglinide",
                                          "nateglinide",
                                          "chlorpropamide",
                                          "glimepiride",
                                          "glipizide",
                                          "glyburide",
                                          "pioglitazone",
                                          "rosiglitazone",
                                          "acarbose",
                                          "insulin",
                                          "glyburide-metformin")],
                           A1C_char_columns, all.x = TRUE)
```


```{r}
# Assessing imbalance with treatment variable
plot(A1C_inference1_dt$A1Cresult_measured, main = "Control - Treatment")
sum(A1C_inference1_dt$A1Cresult_measured == 1)
```

```{r}
## ADJUSTING FOR IMBALANCE BETWEEN TREATMENT/CONTROL: RANDOM UNDER SAMPLING

# creating separate data tables for measured and unmeasured A1C
A1C_unmeasured_dt <- A1C_inference1_dt[A1Cresult_measured==0]
A1C_measured_dt <- A1C_inference1_dt[A1Cresult_measured==1]

# randomly under sampling majority control group
set.seed(123)
A1C_unmeasured_samp <- A1C_unmeasured_dt[sample(nrow(A1C_unmeasured_dt), nrow(A1C_measured_dt), replace = FALSE, prob = NULL), ]


# combining treated group with randomly under sampled majortity/control
A1C_balanced_treatment_DT <- rbindlist(list(A1C_unmeasured_samp, A1C_measured_dt),
                            use.names = TRUE)

sum(A1C_balanced_treatment_DT$A1Cresult_measured==0)
sum(A1C_balanced_treatment_DT$A1Cresult_measured==1)

# removing intermediate data.tables
rm(A1C_unmeasured_dt, A1C_measured_dt, A1C_unmeasured_samp)
```

```{r}
# Assessing class imbalance with outcome variable
plot(A1C_balanced_treatment_DT$readmitted_binary, main = "Outcome Classes")
sum(A1C_balanced_treatment_DT$readmitted_binary==0)
sum(A1C_balanced_treatment_DT$readmitted_binary==1)
```

```{r}
# UPSAMPLING MINORITY CLASS READMITTED = 1

# creating separate data tables for measured and unmeasured A1C
A1C_nonreadmitted_dt <- A1C_balanced_treatment_DT[readmitted_binary==0]
A1C_readmitted_dt <- A1C_balanced_treatment_DT[readmitted_binary==1]

# randomly under sampling majority control group
set.seed(321)
A1C_readmitted_samp <- A1C_readmitted_dt[sample(nrow(A1C_nonreadmitted_dt) - nrow(A1C_readmitted_dt), replace = FALSE, prob = NULL), ]


# combining treated group with randomly under sampled majortity/control
A1C_Analyis_DT <- rbindlist(list(A1C_readmitted_samp, A1C_balanced_treatment_DT),
                            use.names = TRUE)

sum(A1C_Analyis_DT$readmitted_binary==0)
sum(A1C_Analyis_DT$readmitted_binary==1)

# removing intermediate data.tables
rm(A1C_nonreadmitted_dt, A1C_readmitted_dt, A1C_readmitted_samp)
```


```{r}
fit.1 <- glm(unfavorable_outcome ~ . - patient_nbr - encounter_id, 
             data = A1C_balanced_treatment_DT, family = "binomial")
```

```{r}
summary_fit.1 <- summary(fit.1)
variables_fit.1 <- as.data.table(rownames(summary_fit.1$coefficients))
coefficients_fit.1 <- as.data.table(summary_fit.1$coefficients)
coefficients_fit.1 <- coefficients_fit.1[, Sig := ifelse(`Pr(>|z|)` < 0.001, "***", 
                                                         ifelse(`Pr(>|z|)` < 0.01, "**",
                                                                ifelse(`Pr(>|z|)` < 0.05, "*", "")))]
abbreviated_covariates_fit.1 <- str_trunc(variables_fit.1, 150) 
summary_fit.1_dt <- cbind(variables_fit.1, coefficients_fit.1)
```

```{r}
kable(summary_fit.1_dt, digits = 4) %>% 
  kable_styling(font_size = 7, latex_options = "striped") %>% 
    add_header_above(c("Logistic Regression" = 6))
rm(variables_fit.1, coefficients_fit.1)
```







```{r}
# Research Question 2: Is higher AIC measurement associated with unfavorable outcomes?
```






```{r}
# ADDITIONAL CODE
```

```{r}
# Abbreviating expressions in discharge disposition for cleaner regression output (if var is included)
diab_dt$discharge_type <- 
    ifelse(diab_dt$discharge_type == "Discharged to home",
           "Discharged - home",
    ifelse(diab_dt$discharge_type == "Discharged/transferred to SNF",
           "Discharged - SNF",
    ifelse(diab_dt$discharge_type == "Discharged/transferred to home with home health service", 
           "Discharged - home with home health service",
    ifelse(diab_dt$discharge_type == "Discharged/transferred to another short term hospital", 
           "Discharged - short term hospital",
    ifelse(diab_dt$discharge_type == "Discharged/transferred to another type of inpatient care institution", 
           "Discharged - another institution for inpatient care",
    ifelse(diab_dt$discharge_type == "Discharged/transferred to ICF",
           "Discharged - ICF",
    ifelse(diab_dt$discharge_type == "Hospice / medical facility",
           "Hospice - medical facility",
    ifelse(diab_dt$discharge_type == "Discharged/transferred to home under care of Home IV provider", 
           "Discharged - home under care of Home IV provider",
    ifelse(diab_dt$discharge_type == "Hospice / home",  
           "Hospice - home",
    ifelse(diab_dt$discharge_type == "Discharged/transferred/referred another institution for outpatient services",
           "Discharged - another institution for outpatient services",   
    ifelse(diab_dt$discharge_type == "Discharged/transferred to another rehab fac including rehab units of a hospital .",
           "Discharged - rehab facility",
    ifelse(diab_dt$discharge_type == "Discharged/transferred to a long term care hospital.", 
           "Discharged - long term care hospital",                                       
    ifelse(diab_dt$discharge_type == "Expired in a medical facility. Medicaid only, hospice.", 
           "Expired - at medical facility. Medicaid only, hospice.",                 
    ifelse(diab_dt$discharge_type == "Discharged/transferred within this institution to Medicare approved swing bed", 
           "Discharged - within this institution to Medicare approved swing bed",
           ifelse(diab_dt$discharge_type == "Discharged/transferred to a nursing facility certified under Medicaid but not certified under Medicare.", 
                  "Discharged - nursing facility certified under Medicaid but not Medicare.",
         ifelse(diab_dt$discharge_type == "Discharged/transferred/referred to a psychiatric hospital of psychiatric distinct part unit of a hospital", 
                "Discharged -  psychiatric hospital or unit",
          ifelse(diab_dt$discharge_type == "Expired at home. Medicaid only, hospice.", 
                 "Expired - at home. Medicaid only, hospice.",
          ifelse(diab_dt$discharge_type == "Discharged/transferred to a federal health care facility.", 
                 "Discharged - to a federal health care facility.", diab_dt$discharge_type))))))))))))))))))

print(unique(diab_dt$discharge_type))
```




